#!/bin/bash

set -e

# create and truncate readme
touch README.md
echo '<!-- WARNING THIS FILE IS AUTOGENERATED BY build_readme.sh DO NOT EDIT -->' > README.md


while read LINE ; do
    if [[ $LINE == '!!EXEC '* ]]; then
        execline=${LINE#'!!EXEC '}
        eval "$execline >> README.md"
    else
        echo "$LINE" >> README.md
    fi
done < README.md.tpl
